/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:35:24 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;
import java.util.Set;

import org.apache.struts.action.ActionForm;

/**
 * A class that represents a row in the td_sm_job table. You can customize the
 * behavior of this class by editing the class, {@link Job()}. WARNING: DO
 * NOT EDIT THIS FILE. This is a generated file that is synchronized * by
 * MyEclipse Hibernate tool integration.
 */
public abstract class AbstractJob   implements Serializable {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** The composite primary key value. */
    private String jobId;

    /** The value of the simple jobName property. */
    private String jobName;

    /** The value of the simple jobDesc property. */
    private String jobDesc;
    
    /**岗位职责*/
    private String jobFunction;
    
    /**岗位编制人数*/
    private String jobAmount;
    
    /**岗位编号*/
    private String jobNumber;
    
    /**任职条件*/
    private String jobCondition;
    
    
    /**岗位等级*/
    private String jobRank;
    
    /**岗位创建人ID*/
    private int owner_id;

    /**
     * 用户、岗位、机构实体集合
     */
    private Set userjoborgSet = null;

    /**
     * 机构和岗位实体集合
     */
    private Set orgjobSet = null;

    /**
     * @return 返回 orgjobSet。
     */
    public Set getOrgjobSet() {
        return orgjobSet;
    }

    /**
     * @param orgjobSet
     *            要设置的 orgjobSet。
     */
    public void setOrgjobSet(Set orgjobSet) {
        this.orgjobSet = orgjobSet;
    }

    /**
     * Simple constructor of AbstractJob instances.
     */
    public AbstractJob() {
    }

    /**
     * Constructor of AbstractJob instances given a simple primary key.
     * 
     * @param jobId
     */
    public AbstractJob(String jobId) {
        this.setJobId(jobId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * 
     * @return String
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * 
     * @param jobId
     */
    public void setJobId(String jobId) {
        this.hashValue = 0;
        this.jobId = jobId;
    }

    /**
     * Return the value of the JOB_NAME column.
     * 
     * @return String
     */
    public String getJobName() {
        return this.jobName;
    }

    /**
     * Set the value of the JOB_NAME column.
     * 
     * @param jobName
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * Return the value of the JOB_DESC column.
     * 
     * @return String
     */
    public String getJobDesc() {
        return this.jobDesc;
    }

    /**
     * Set the value of the JOB_DESC column.
     * 
     * @param jobDesc
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Job))
            return false;
        Job that = (Job) rhs;
        if (this.getJobId() != null && that.getJobId() != null) {
            if (!this.getJobId().equals(that.getJobId())) {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int jobIdValue = this.getJobId() == null ? 0 : this.getJobId()
                    .hashCode();
            result = result * 37 + jobIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

    /**
     * @return 返回 userjoborgSet。
     */
    public Set getUserjoborgSet() {
        return userjoborgSet;
    }

    /**
     * @param userjoborgSet
     *            要设置的 userjoborgSet。
     */
    public void setUserjoborgSet(Set userjoborgSet) {
        this.userjoborgSet = userjoborgSet;
    }

	public String getJobAmount() {
		return jobAmount;
	}

	public void setJobAmount(String jobAmount) {
		this.jobAmount = jobAmount;
	}

	public String getJobCondition() {
		return jobCondition;
	}

	public void setJobCondition(String jobCondition) {
		this.jobCondition = jobCondition;
	}

	public String getJobFunction() {
		return jobFunction;
	}

	public void setJobFunction(String jobFunction) {
		this.jobFunction = jobFunction;
	}

	public String getJobNumber() {
		return jobNumber;
	}

	public void setJobNumber(String jobNumber) {
		this.jobNumber = jobNumber;
	}

	public String getJobRank() {
		return jobRank;
	}

	public void setJobRank(String jobRank) {
		this.jobRank = jobRank;
	}

	public int getOwner_id() {
		return owner_id;
	}

	public void setOwner_id(int owner_id) {
		this.owner_id = owner_id;
	}

	
}