package com.frameworkset.platform.sysmgrcore.entity;

import java.util.Set;

/**
 * AbstractTdSmDicttype generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDicttype implements java.io.Serializable {

	// Fields

	private String dicttypeId;

	private String dicttypeName;

	private String dicttypeDesc;

	private String dicttypeParent;

	private Set dictdataSet;

	// Constructors

	/** default constructor */
	public AbstractDicttype() {
	}

	/** full constructor */
	public AbstractDicttype(String dicttypeName, String dicttypeDesc,
			String dicttypeParent) {
		this.dicttypeName = dicttypeName;
		this.dicttypeDesc = dicttypeDesc;
		this.dicttypeParent = dicttypeParent;
	}

	// Property accessors

	public String getDicttypeId() {
		return this.dicttypeId;
	}

	public void setDicttypeId(String dicttypeId) {
		this.dicttypeId = dicttypeId;
	}

	public String getDicttypeName() {
		return this.dicttypeName;
	}

	public void setDicttypeName(String dicttypeName) {
		this.dicttypeName = dicttypeName;
	}

	public String getDicttypeDesc() {
		return this.dicttypeDesc;
	}

	public void setDicttypeDesc(String dicttypeDesc) {
		this.dicttypeDesc = dicttypeDesc;
	}

	public String getDicttypeParent() {
		return this.dicttypeParent;
	}

	public void setDicttypeParent(String dicttypeParent) {
		this.dicttypeParent = dicttypeParent;
	}

	public Set getDictdataSet() {
		return dictdataSet;
	}

	public void setDictdataSet(Set dictdataSet) {
		this.dictdataSet = dictdataSet;
	}

}