/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:34:17 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;
import java.sql.Date;

/**
 * A class that represents a row in the td_sm_accredit table. You can customize
 * the behavior of this class by editing the class, {@link Accredit()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized *
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractAccredit implements Serializable {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** The composite primary key value. */
    private String accreditId;

    /** The value of the simple userId property. */
    private Integer userId;

    /** The value of the simple accreditUserId property. */
    private String accreditUserId;

    /** The value of the simple validfrom property. */
    private Date validfrom;

    /** The value of the simple validto property. */
    private Date validto;

    /**
     * 需要授权的用户
     */
    private User user = null;

    /**
     * 接受授权的用户实体
     */
    private User accreditUser = null;

    /**
     * @return 返回 user。
     */
    public User getUser() {
        return user;
    }

    /**
     * @param user
     *            要设置的 user。
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @return 返回 accreditUser。
     */
    public User getAccreditUser() {
        return accreditUser;
    }

    /**
     * @param accreditUser
     *            要设置的 accreditUser。
     */
    public void setAccreditUser(User accreditUser) {
        this.accreditUser = accreditUser;
    }

    /**
     * Simple constructor of AbstractAccredit instances.
     */
    public AbstractAccredit() {
    }

    /**
     * Constructor of AbstractAccredit instances given a simple primary key.
     * 
     * @param accreditId
     */
    public AbstractAccredit(String accreditId) {
        this.setAccreditId(accreditId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * 
     * @return String
     */
    public String getAccreditId() {
        return accreditId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * 
     * @param accreditId
     */
    public void setAccreditId(String accreditId) {
        this.hashValue = 0;
        this.accreditId = accreditId;
    }

    /**
     * Return the value of the USER_ID column.
     * 
     * @return String
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Set the value of the USER_ID column.
     * 
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Return the value of the ACCREDIT_USER_ID column.
     * 
     * @return String
     */
    public String getAccreditUserId() {
        return this.accreditUserId;
    }

    /**
     * Set the value of the ACCREDIT_USER_ID column.
     * 
     * @param accreditUserId
     */
    public void setAccreditUserId(String accreditUserId) {
        this.accreditUserId = accreditUserId;
    }

    /**
     * Return the value of the VALIDFROM column.
     * 
     * @return java.util.Date
     */
    public java.util.Date getValidfrom() {
        return this.validfrom;
    }

    /**
     * Set the value of the VALIDFROM column.
     * 
     * @param validfrom
     */
    public void setValidfrom(Date validfrom) {
        this.validfrom = validfrom;
    }

    /**
     * Return the value of the VALIDTO column.
     * 
     * @return java.util.Date
     */
    public java.util.Date getValidto() {
        return this.validto;
    }

    /**
     * Set the value of the VALIDTO column.
     * 
     * @param validto
     */
    public void setValidto(Date validto) {
        this.validto = validto;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Accredit))
            return false;
        Accredit that = (Accredit) rhs;
        if (this.getAccreditId() != null && that.getAccreditId() != null) {
            if (!this.getAccreditId().equals(that.getAccreditId())) {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int accreditIdValue = this.getAccreditId() == null ? 0 : this
                    .getAccreditId().hashCode();
            result = result * 37 + accreditIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}