/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:34:47 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the td_sm_groupexp table. You can customize
 * the behavior of this class by editing the class, {@link Groupexp()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized *
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractGroupexp implements Serializable {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** The composite primary key value. */
    private String groupexpId;

    /** The value of the simple groupId property. */
    private Integer groupId;

    /** The value of the simple sqlexp property. */
    private String sqlexp;

    /**
     * 所关联的组实体
     */
    private Group group = null;

    /**
     * @return 返回 group。
     */
    public Group getGroup() {
        return group;
    }

    /**
     * @param group
     *            要设置的 group。
     */
    public void setGroup(Group group) {
        this.group = group;
    }

    /**
     * Simple constructor of AbstractGroupexp instances.
     */
    public AbstractGroupexp() {
    }

    /**
     * Constructor of AbstractGroupexp instances given a simple primary key.
     * 
     * @param groupexpId
     */
    public AbstractGroupexp(String groupexpId) {
        this.setGroupexpId(groupexpId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * 
     * @return String
     */
    public String getGroupexpId() {
        return groupexpId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * 
     * @param groupexpId
     */
    public void setGroupexpId(String groupexpId) {
        this.hashValue = 0;
        this.groupexpId = groupexpId;
    }

    /**
     * Return the value of the GROUP_ID column.
     * 
     * @return String
     */
    public Integer getGroupId() {
        return this.groupId;
    }

    /**
     * Set the value of the GROUP_ID column.
     * 
     * @param groupId
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * Return the value of the SQLEXP column.
     * 
     * @return String
     */
    public String getSqlexp() {
        return this.sqlexp;
    }

    /**
     * Set the value of the SQLEXP column.
     * 
     * @param sqlexp
     */
    public void setSqlexp(String sqlexp) {
        this.sqlexp = sqlexp;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Groupexp))
            return false;
        Groupexp that = (Groupexp) rhs;
        if (this.getGroupexpId() != null && that.getGroupexpId() != null) {
            if (!this.getGroupexpId().equals(that.getGroupexpId())) {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int groupexpIdValue = this.getGroupexpId() == null ? 0 : this
                    .getGroupexpId().hashCode();
            result = result * 37 + groupexpIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}