/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Mar 15 16:22:22 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the TD_SM_OPERGROUP table. 
 * You can customize the behavior of this class by editing the class, {@link TdSmOpergroup()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractOpergroup 
    implements Serializable
{

    /** The composite primary key value. */
    private java.lang.String groupId;

    /** The value of the simple groupName property. */
    private java.lang.String groupName;

    /** The value of the simple groupDesc property. */
    private java.lang.String groupDesc;

    /**
     * Simple constructor of AbstractTdSmOpergroup instances.
     */
    public AbstractOpergroup()
    {
    }

    /**
     * Constructor of AbstractTdSmOpergroup instances given a simple primary key.
     * @param groupId
     */
    public AbstractOpergroup(java.lang.String groupId)
    {
        this.setGroupId(groupId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getGroupId()
    {
        return groupId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param groupId
     */
    public void setGroupId(java.lang.String groupId)
    {
        this.groupId = groupId;
    }

    /**
     * Return the value of the GROUP_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getGroupName()
    {
        return this.groupName;
    }

    /**
     * Set the value of the GROUP_NAME column.
     * @param groupName
     */
    public void setGroupName(java.lang.String groupName)
    {
        this.groupName = groupName;
    }

    /**
     * Return the value of the GROUP_DESC column.
     * @return java.lang.String
     */
    public java.lang.String getGroupDesc()
    {
        return this.groupDesc;
    }

    /**
     * Set the value of the GROUP_DESC column.
     * @param groupDesc
     */
    public void setGroupDesc(java.lang.String groupDesc)
    {
        this.groupDesc = groupDesc;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Opergroup))
            return false;
        Opergroup that = (Opergroup) rhs;
        if (this.getGroupId() != null && that.getGroupId() != null)
        {
            if (! this.getGroupId().equals(that.getGroupId()))
            {
                return false;
            }
        }
        return true;
    }

}
