package com.frameworkset.platform.sysmgrcore.entity;

/**
 * AbstractTdSmGrouprole generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractGrouprole implements java.io.Serializable {

	// Fields

	private GrouproleId id = new GrouproleId();

	/**
	 * 所关联的组对象实例
	 */
	private Group group;

	/**
	 * 所关联的角色对象实例
	 */
	private Role role;

	// Constructors

	/** default constructor */
	public AbstractGrouprole() {
	}

	// Property accessors

	public GrouproleId getId() {
		return this.id;
	}

	public void setId(GrouproleId id) {
		this.id = id;
	}

	public Group getGroup() {
		return group;
	}

	public void setGroup(Group group) {
		this.group = group;
		id.setGroupId(group.getGroupId());
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
		
		if (id.getRoleId() == null && role != null)
			id.setRoleId(role.getRoleId());
	}
}