/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:37:14 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;
import java.util.Set;

/**
 * A class that represents a row in the td_sm_role table. You can customize the
 * behavior of this class by editing the class, {@link Role()}. WARNING: DO NOT
 * EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse
 * Hibernate tool integration.
 * @@org.jboss.cache.aop.AopMarker
 */
public abstract class AbstractRole implements Serializable {

	/** The composite primary key value. */
	private String roleId;

	/** The value of the simple roleName property. */
	private String roleName;

	/** The value of the simple roleType property. */
	private String roleType;

	/** The value of the simple roleDesc property. */
	private String roleDesc;

	/** The value of the simple roleUsage property. */
	private String roleUsage;

	/** The value of the simple remark1 property. */
	private String remark1;

	/** The value of the simple remark2 property. */
	private String remark2;

	/** The value of the simple remark3 property. */
	private String remark3;

	/**
	 * 角色实体所关联的用户角色实体
	 */
	private Set userroleSet = null;

	/**
	 * 角色资源操作实体集合
	 */
	private Set roleresopSet = null;

	/**
	 * 组与角色实体集合
	 */
	private Set grouproleSet = null;
	
	/**
	 * 角色的创建人的id，默认为系统管理员id为1
	 */
	private int owner_id;

	public int getOwner_id() {
		return owner_id;
	}

	public void setOwner_id(int owner_id) {
		this.owner_id = owner_id;
	}

	public Set getGrouproleSet() {
		return grouproleSet;
	}

	public void setGrouproleSet(Set grouproleSet) {
		this.grouproleSet = grouproleSet;
	}

	/**
	 * @return 返回 roleresopSet。
	 */
	public Set getRoleresopSet() {
		return roleresopSet;
	}

	/**
	 * @param roleresopSet
	 *            要设置的 roleresopSet。
	 */
	public void setRoleresopSet(Set roleresopSet) {
		this.roleresopSet = roleresopSet;
	}

	/**
	 * @return 返回 userroleSet。
	 */
	public Set getUserroleSet() {
		return userroleSet;
	}

	/**
	 * @param userroleSet
	 *            要设置的 userroleSet。
	 */
	public void setUserroleSet(Set userroleSet) {
		this.userroleSet = userroleSet;
	}

	/**
	 * Simple constructor of AbstractRole instances.
	 */
	public AbstractRole() {
	}

	/**
	 * Constructor of AbstractRole instances given a simple primary key.
	 * 
	 * @param roleId
	 */
	public AbstractRole(String roleId) {
		this.setRoleId(roleId);
	}

	/**
	 * Return the simple primary key value that identifies this object.
	 * 
	 * @return String
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * Set the simple primary key value that identifies this object.
	 * 
	 * @param roleId
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * Return the value of the ROLE_NAME column.
	 * 
	 * @return String
	 */
	public String getRoleName() {
		return this.roleName;
	}

	/**
	 * Set the value of the ROLE_NAME column.
	 * 
	 * @param roleName
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * Return the value of the ROLE_TYPE column.
	 * 
	 * @return String
	 */
	public String getRoleType() {
		return this.roleType;
	}

	/**
	 * Set the value of the ROLE_TYPE column.
	 * 
	 * @param roleType
	 */
	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	/**
	 * Return the value of the ROLE_DESC column.
	 * 
	 * @return String
	 */
	public String getRoleDesc() {
		return this.roleDesc;
	}

	/**
	 * Set the value of the ROLE_DESC column.
	 * 
	 * @param roleDesc
	 */
	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	/**
	 * Return the value of the ROLE_USAGE column.
	 * 
	 * @return String
	 */
	public String getRoleUsage() {
		return this.roleUsage;
	}

	/**
	 * Set the value of the ROLE_USAGE column.
	 * 
	 * @param roleUsage
	 */
	public void setRoleUsage(String roleUsage) {
		this.roleUsage = roleUsage;
	}

	/**
	 * Return the value of the REMARK1 column.
	 * 
	 * @return String
	 */
	public String getRemark1() {
		return this.remark1;
	}

	/**
	 * Set the value of the REMARK1 column.
	 * 
	 * @param remark1
	 */
	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	/**
	 * Return the value of the REMARK2 column.
	 * 
	 * @return String
	 */
	public String getRemark2() {
		return this.remark2;
	}

	/**
	 * Set the value of the REMARK2 column.
	 * 
	 * @param remark2
	 */
	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	/**
	 * Return the value of the REMARK3 column.
	 * 
	 * @return String
	 */
	public String getRemark3() {
		return this.remark3;
	}

	/**
	 * Set the value of the REMARK3 column.
	 * 
	 * @param remark3
	 */
	public void setRemark3(String remark3) {
		this.remark3 = remark3;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the
	 * primary key values.
	 * 
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof Role))
			return false;
		Role that = (Role) rhs;
		if (this.getRoleId() != null && that.getRoleId() != null) {
			if (!this.getRoleId().equals(that.getRoleId())) {
				return false;
			}
		}
		return true;
	}

}