/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:34:35 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;
import java.util.Set;

/**
 * A class that represents a row in the td_sm_group table. You can customize the
 * behavior of this class by editing the class, {@link Group()}. WARNING: DO
 * NOT EDIT THIS FILE. This is a generated file that is synchronized * by
 * MyEclipse Hibernate tool integration.
 */
public abstract class AbstractGroup implements Serializable {
	/**
	 * The cached hash code value for this instance. Settting to 0 triggers
	 * re-calculation.
	 */
	private int hashValue = 0;

	/** The composite primary key value. */
	private int groupId;

	/**
	 * 当前组的父组ID，为0时表示没有父组
	 */
	private int parentId;

	/** The value of the simple groupName property. */
	private String groupName;

	/** The value of the simple groupDesc property. */
	private String groupDesc;

	/** The value of the simple remark1 property. */
	private String remark1;

	/** The value of the simple remark2 property. */
	private String remark2;

	/** The value of the simple remark3 property. */
	private String remark3;

	/** The value of the simple remark4 property. */
	private String remark4;

	/** The value of the simple remark5 property. */
	private String remark5;

	
	private String grouptreelevel;
	public String getGrouptreelevel() {
		return grouptreelevel;
	}

	public void setGrouptreelevel(String grouptreelevel) {
		this.grouptreelevel = grouptreelevel;
	}

	/**
	 * 动态组表达式集合
	 */
	private Set groupexpSet = null;

	/**
	 * 用户组集合
	 */
	private Set usergroupSet = null;

	/**
	 * 机构和组实体集合
	 */
	private Set orggroupSet = null;

	/**
	 * 组与角色实体集合
	 */
	private Set grouproleSet = null;

	/**
	 * 当前组的父用户组
	 */
	private Group parentGroup = null;
	
	/**
	 * 创建人的id
	 * */
	private int owner_id;

	public Group getParentGroup() {
		return parentGroup;
	}

	public void setParentGroup(Group parentGroup) {
		this.parentGroup = parentGroup;
		
		if ( parentGroup != null)
			this.parentId = parentGroup.getParentId();
	}

	public int getParentId() {
		return parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	/**
	 * @return 返回 groupexpSet。
	 */
	public Set getGroupexpSet() {
		return groupexpSet;
	}

	public Set getGrouproleSet() {
		return grouproleSet;
	}

	public void setGrouproleSet(Set grouproleSet) {
		this.grouproleSet = grouproleSet;
	}

	/**
	 * @param groupexpSet
	 *            要设置的 groupexpSet。
	 */
	public void setGroupexpSet(Set groupexpSet) {
		this.groupexpSet = groupexpSet;
	}

	/**
	 * @return 返回 orggroupSet。
	 */
	public Set getOrggroupSet() {
		return orggroupSet;
	}

	/**
	 * @param orggroupSet
	 *            要设置的 orggroupSet。
	 */
	public void setOrggroupSet(Set orggroupSet) {
		this.orggroupSet = orggroupSet;
	}

	/**
	 * @return 返回 usergroupSet。
	 */
	public Set getUsergroupSet() {
		return usergroupSet;
	}

	/**
	 * @param usergroupSet
	 *            要设置的 usergroupSet。
	 */
	public void setUsergroupSet(Set usergroupSet) {
		this.usergroupSet = usergroupSet;
	}

	/**
	 * Simple constructor of AbstractGroup instances.
	 */
	public AbstractGroup() {
	}

	/**
	 * Constructor of AbstractGroup instances given a simple primary key.
	 * 
	 * @param groupId
	 */
	public AbstractGroup(int groupId) {
		this.setGroupId(groupId);
	}

	/**
	 * Return the simple primary key value that identifies this object.
	 * 
	 * @return String
	 */
	public int getGroupId() {
		return groupId;
	}

	/**
	 * Set the simple primary key value that identifies this object.
	 * 
	 * @param groupId
	 */
	public void setGroupId(int groupId) {
		this.hashValue = 0;
		this.groupId = groupId;
	}

	/**
	 * Return the value of the GROUP_NAME column.
	 * 
	 * @return String
	 */
	public String getGroupName() {
		return this.groupName;
	}

	/**
	 * Set the value of the GROUP_NAME column.
	 * 
	 * @param groupName
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * Return the value of the GROUP_DESC column.
	 * 
	 * @return String
	 */
	public String getGroupDesc() {
		return this.groupDesc;
	}

	/**
	 * Set the value of the GROUP_DESC column.
	 * 
	 * @param groupDesc
	 */
	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	/**
	 * Return the value of the REMARK1 column.
	 * 
	 * @return String
	 */
	public String getRemark1() {
		return this.remark1;
	}

	/**
	 * Set the value of the REMARK1 column.
	 * 
	 * @param remark1
	 */
	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	/**
	 * Return the value of the REMARK2 column.
	 * 
	 * @return String
	 */
	public String getRemark2() {
		return this.remark2;
	}

	/**
	 * Set the value of the REMARK2 column.
	 * 
	 * @param remark2
	 */
	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	/**
	 * Return the value of the REMARK3 column.
	 * 
	 * @return String
	 */
	public String getRemark3() {
		return this.remark3;
	}

	/**
	 * Set the value of the REMARK3 column.
	 * 
	 * @param remark3
	 */
	public void setRemark3(String remark3) {
		this.remark3 = remark3;
	}

	/**
	 * Return the value of the REMARK4 column.
	 * 
	 * @return String
	 */
	public String getRemark4() {
		return this.remark4;
	}

	/**
	 * Set the value of the REMARK4 column.
	 * 
	 * @param remark4
	 */
	public void setRemark4(String remark4) {
		this.remark4 = remark4;
	}

	/**
	 * Return the value of the REMARK5 column.
	 * 
	 * @return String
	 */
	public String getRemark5() {
		return this.remark5;
	}

	/**
	 * Set the value of the REMARK5 column.
	 * 
	 * @param remark5
	 */
	public void setRemark5(String remark5) {
		this.remark5 = remark5;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the
	 * primary key values.
	 * 
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof Group))
			return false;
		Group that = (Group) rhs;
		return this.getGroupId()== that.getGroupId();
				
			
		
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern
	 * with the exception of array properties (these are very unlikely primary
	 * key types).
	 * 
	 * @return int
	 */
	public int hashCode() {
		if (this.hashValue == 0) {
			int result = 17;
			result = result * 37 + this.groupId;
			this.hashValue = result;
		}
		return this.hashValue;
	}

	public int getOwner_id() {
		return owner_id;
	}

	public void setOwner_id(int owner_id) {
		this.owner_id = owner_id;
	}
}