/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:37:24 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the td_sm_roleresop table. You can customize
 * the behavior of this class by editing the class, {@link Roleresop()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized *
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractRoleresop implements Serializable {

    /** The simple primary key value. */
    private RoleresopKey id = new RoleresopKey();

    /**
     * 所关联的角色实体
     */
    private Role role = null;

    /**
     * 所关联的资源实体
     */
    private Res res = null;

    /**
     * 所关联的操作实体
     */
    private Operation operation = null;

    /**
     * 所关联的操作实体
     */
    private Restype restype = null;
    
    /**
     * 资源名称
     */
    private String resName = null;
    
    /**
     * 标识资源维护方式，0自动维护，1手动维护
     */
    private String auto = null;
    
    private String opId;
    private String resId;
    private String roleId;
    private String restypeId;
    private String types;
    private String opName;//操作名称
    private String resTypeName;
    /**
     * @return 返回 operation。
     */
    public Operation getOperation() {
        return operation;
    }

    /**
     * @param operation
     *            要设置的 operation。
     */
    public void setOperation(Operation operation) {
        this.operation = operation;

        if (id.getOpId() == null && operation != null)
            id.setOpId(operation.getOpId());
    }

    /**
     * @return 返回 res。
     */
    public Res getRes() {
        return res;
    }

    /**
     * @param res
     *            要设置的 res。
     */
    public void setRes(Res res) {
        this.res = res;

        if (id.getResId() == null && res != null)
            res.setResId(res.getResId());
    }

    /**
     * @return 返回 role。
     */
    public Role getRole() {
        return role;
    }

    /**
     * @param role
     *            要设置的 role。
     */
    public void setRole(Role role) {
        this.role = role;

        if (id.getRoleId() == null && role != null)
            id.setRoleId(role.getRoleId());
    }

    /**
     * @return 返回 restype。
     */
    public Restype getRestype() {
        return restype;
    }

    /**
     * @param role
     *            要设置的 restype。
     */
    public void setRestype(Restype restype) {
        this.restype = restype;

        if (id.getRestypeId() == null && restype != null)
            id.setRestypeId(restype.getRestypeId());
    }

    /**
     * Simple constructor of AbstractRoleresop instances.
     */
    public AbstractRoleresop() {
    }

    /**
     * Constructor of AbstractRoleresop instances given a composite primary
     * key.
     * 
     * @param id
     */
    public AbstractRoleresop(RoleresopKey id) {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * 
     * @return RoleresopKey
     */
    public RoleresopKey getId() {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * 
     * @param id
     */
    public void setId(RoleresopKey id) {
        this.id = id;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Roleresop))
            return false;
        Roleresop that = (Roleresop) rhs;
        if (this.getId() != null && that.getId() != null) {
            return (this.getId().equals(that.getId()));
        }
        return true;
    }

    /**
     * @return Returns the resName.
     */
    public String getResName() {
        return resName;
    }
    /**
     * @param resName The resName to set.
     */
    public void setResName(String resName) {
        this.resName = resName;
    }
    /**
     * @return Returns the auto.
     */
    public String getAuto() {
        return auto;
    }
    /**
     * @param auto The auto to set.
     */
    public void setAuto(String auto) {
        this.auto = auto;
    }

	public String getOpId() {
		return opId;
	}

	public void setOpId(String opId) {
		this.opId = opId;
	}

	public String getResId() {
		return resId;
	}

	public void setResId(String resId) {
		this.resId = resId;
	}

	public String getRestypeId() {
		return restypeId;
	}

	public void setRestypeId(String restypeId) {
		this.restypeId = restypeId;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getTypes() {
		return types;
	}

	public void setTypes(String types) {
		this.types = types;
	}

	public String getOpName() {
		return opName;
	}

	public void setOpName(String opName) {
		this.opName = opName;
	}

	public String getResTypeName() {
		return resTypeName;
	}

	public void setResTypeName(String resTypeName) {
		this.resTypeName = resTypeName;
	}
}