/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:36:08 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;
import java.util.Set;


/**
 * A class that represents a row in the td_sm_operations table. You can
 * customize the behavior of this class by editing the class,
 * {@link Operation()}. WARNING: DO NOT EDIT THIS FILE. This is a generated
 * file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractOperation  implements Serializable {
 

    /** The composite primary key value. */
    private String opId;
    
    /** The value of the simple opName property. */
    private String opName;    

    /** The value of the simple opDes property. */
    private String opDes;

    /** The value of the simple priority property. */
    private String priority;

    /** The value of the simple reserved1 property. */
    private String reserved1;

    /** The value of the simple reserved2 property. */
    private String reserved2;

    /** The value of the simple reserved3 property. */
    private String reserved3;

    /** The value of the simple reserved4 property. */
    private String reserved4;

    /** The value of the simple reserved5 property. */
    private String reserved5;

    /**
     * 用户资源操作集合
     */
    private Set userresopSet = null;

    /**
     * 临时授权
     */
    private Set tempaccreditSet = null;

    /**
     * 角色资源操作实体集合
     */
    private Set roleresopSet = null;

    /**
     * 操作资源集合
     */
    private Set operresSet = null;

    /**
     * @return 返回 operresSet。
     */
    public Set getOperresSet() {
        return operresSet;
    }

    /**
     * @param operresSet
     *            要设置的 operresSet。
     */
    public void setOperresSet(Set operresSet) {
        this.operresSet = operresSet;
    }

    /**
     * @return 返回 roleresopSet。
     */
    public Set getRoleresopSet() {
        return roleresopSet;
    }

    /**
     * @param roleresopSet
     *            要设置的 roleresopSet。
     */
    public void setRoleresopSet(Set roleresopSet) {
        this.roleresopSet = roleresopSet;
    }

    /**
     * @return 返回 tempaccreditSet。
     */
    public Set getTempaccreditSet() {
        return tempaccreditSet;
    }

    /**
     * @param tempaccreditSet
     *            要设置的 tempaccreditSet。
     */
    public void setTempaccreditSet(Set tempaccreditSet) {
        this.tempaccreditSet = tempaccreditSet;
    }

    /**
     * @return 返回 userresopSet。
     */
    public Set getUserresopSet() {
        return userresopSet;
    }

    /**
     * @param userresopSet
     *            要设置的 userresopSet。
     */
    public void setUserresopSet(Set userresopSet) {
        this.userresopSet = userresopSet;
    }

    /**
     * Simple constructor of AbstractOperation instances.
     */
    public AbstractOperation() {
    }

    /**
     * Constructor of AbstractOperation instances given a simple primary
     * key.
     * 
     * @param opId
     */
    public AbstractOperation(String opId) {
        this.setOpId(opId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * 
     * @return String
     */
    public String getOpId() {
        return opId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * 
     * @param opId
     */
    public void setOpId(String opId) {
      
        this.opId = opId;
    }

    /**
     * Return the value of the OP_NAME column.
     * 
     * @return String
     */
    public String getOpName() {
        return this.opName;
    }

    /**
     * Set the value of the OP_NAME column.
     * 
     * @param opName
     */
    public void setOpName(String opName) {
        this.opName = opName;
    }

    /**
     * Return the value of the OP_DES column.
     * 
     * @return String
     */
    public String getOpDes() {
        return this.opDes;
    }

    /**
     * Set the value of the OP_DES column.
     * 
     * @param opDes
     */
    public void setOpDes(String opDes) {
        this.opDes = opDes;
    }

    /**
     * Return the value of the PRIORITY column.
     * 
     * @return String
     */
    public String getPriority() {
        return this.priority;
    }

    /**
     * Set the value of the PRIORITY column.
     * 
     * @param priority
     */
    public void setPriority(String priority) {
        this.priority = priority;
    }

    /**
     * Return the value of the RESERVED1 column.
     * 
     * @return String
     */
    public String getReserved1() {
        return this.reserved1;
    }

    /**
     * Set the value of the RESERVED1 column.
     * 
     * @param reserved1
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * Return the value of the RESERVED2 column.
     * 
     * @return String
     */
    public String getReserved2() {
        return this.reserved2;
    }

    /**
     * Set the value of the RESERVED2 column.
     * 
     * @param reserved2
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2;
    }

    /**
     * Return the value of the RESERVED3 column.
     * 
     * @return String
     */
    public String getReserved3() {
        return this.reserved3;
    }

    /**
     * Set the value of the RESERVED3 column.
     * 
     * @param reserved3
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3;
    }

    /**
     * Return the value of the RESERVED4 column.
     * 
     * @return String
     */
    public String getReserved4() {
        return this.reserved4;
    }

    /**
     * Set the value of the RESERVED4 column.
     * 
     * @param reserved4
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4;
    }

    /**
     * Return the value of the RESERVED5 column.
     * 
     * @return String
     */
    public String getReserved5() {
        return this.reserved5;
    }

    /**
     * Set the value of the RESERVED5 column.
     * 
     * @param reserved5
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Operation))
            return false;
        Operation that = (Operation) rhs;
        if (this.getOpId() != null && that.getOpId() != null) {
            if (!this.getOpId().equals(that.getOpId())) {
                return false;
            }
        }
        return true;
    }

    
}