/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Mar 17 08:40:14 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the TD_SM_OPERGPRESTYPE table. 
 * You can customize the behavior of this class by editing the class, {@link Opergprestype()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractOpergprestype 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private OpergprestypeKey id;

    private Opergroup opergroup = null;
    private Restype restype = null;
    /**
     * Simple constructor of AbstractOpergprestype instances.
     */
    public AbstractOpergprestype()
    {
    }

    /**
     * Constructor of AbstractOpergprestype instances given a composite primary key.
     * @param id
     */
    public AbstractOpergprestype(OpergprestypeKey id)
    {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * @return OpergprestypeKey
     */
    public OpergprestypeKey getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(OpergprestypeKey id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Opergprestype))
            return false;
        Opergprestype that = (Opergprestype) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            return (this.getId().equals(that.getId()));
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            if (this.getId() == null)
            {
                result = super.hashCode();
            }
            else
            {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
    
    public Opergroup getOpergroup() {
        return opergroup;
    }

    /**
     * @param Opergroup
     *            要设置的 Opergroup。
     */
    public void setOpergroup(Opergroup opergroup) {
        this.opergroup = opergroup;

        if (id.getGroupId() == null && opergroup != null)
            id.setGroupId(opergroup.getGroupId());
    }
    
    public Restype getRestype() {
        return restype;
    }

    /**
     * @param Opergroup
     *            要设置的 Opergroup。
     */
    public void setRestype(Restype restype) {
        this.restype = restype;

        if (id.getRestypeId() == null && restype != null)
            id.setRestypeId(restype.getRestypeId());
    }            
}
