package com.frameworkset.platform.sysmgrcore.entity;
// Generated by MyEclipse - Hibernate Tools



/**
 * TdSmDictdata generated by MyEclipse - Hibernate Tools
 */
public class Dictdata extends AbstractDictdata implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Dictdata() {
    }

    
    /** full constructor */
    public Dictdata(String dicttypeId, String dictdataName, String dictdataValue,long dictdataOrder) {
        super(dicttypeId, dictdataName, dictdataValue,dictdataOrder);        
    }    
   
}
