package com.frameworkset.platform.sysmgrcore.entity;

// Generated by MyEclipse - Hibernate Tools

/**
 * TdSmDicttype generated by MyEclipse - Hibernate Tools
 */
public class Dicttype extends AbstractDicttype implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Dicttype() {
	}

	/** full constructor */
	public Dicttype(String dicttypeName, String dicttypeDesc,
			String dicttypeParent) {
		super(dicttypeName, dicttypeDesc, dicttypeParent);
	}

}
