package com.frameworkset.platform.sysmgrcore.entity;
// Generated by MyEclipse - Hibernate Tools



/**
 * TdSmGrouprole generated by MyEclipse - Hibernate Tools
 */
public class Grouprole extends AbstractGrouprole implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Grouprole() {
    }
  
   
}
