package com.frameworkset.platform.sysmgrcore.entity;

/**
 * TdSmGrouproleId generated by MyEclipse - Hibernate Tools
 */

public class GrouproleId implements java.io.Serializable {

	// Fields

	private int groupId;

	private String roleId;

	// Constructors

	/** default constructor */
	public GrouproleId() {
	}

	/** full constructor */
	public GrouproleId(int groupId, String roleId) {
		this.groupId = groupId;
		this.roleId = roleId;
	}

	// Property accessors

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrouproleId))
			return false;
		GrouproleId castOther = (GrouproleId) other;

		return ((this.getGroupId() == castOther.getGroupId()))
				&& ((this.getRoleId() == castOther.getRoleId()) || (this
						.getRoleId() != null
						&& castOther.getRoleId() != null && this.getRoleId()
						.equals(castOther.getRoleId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ this.getGroupId();
		result = 37 * result
				+ (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		return result;
	}

}