/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Mar 17 08:40:03 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the TD_SM_OPERGPOPER
 * table.  This object should only be instantiated for use with instances 
 * of the Opergpoper class.
 */
public class OpergpoperKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the GROUP_ID component of this composite id. */
    //private Opergroup Opergroup;
    private String groupId;
    private String opId;

    /** The value of the OP_ID component of this composite id. */
   // private Operation Operation;

    /**
     * Simple constructor of OpergpoperKey instances.
     */
    public OpergpoperKey()
    {
    }

    public String getGroupId()
    {
        return groupId;
    }
 
    public void setGroupId(String groupId)
    {
        hashValue = 0;
        this.groupId = groupId;
    }
    
    public String getOpId()
    {
        return opId;
    }
 
    public void setOpId(String opId)
    {
        hashValue = 0;
        this.opId = opId;
    }


    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof OpergpoperKey))
            return false;
        OpergpoperKey that = (OpergpoperKey) rhs;
        if (this.getOpId() != null && that.getOpId() != null)
        {
            if (! this.getOpId().equals(that.getOpId()))
            {
                return false;
            }
        }
        if (this.getGroupId() != null && that.getGroupId() != null)
        {
            if (! this.getGroupId().equals(that.getGroupId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int opIdValue = this.getOpId() == null ? 0 : this.getOpId().hashCode();
            result = result * 37 + opIdValue;
            int groupIdValue = this.getGroupId() == null ? 0 : this.getGroupId().hashCode();
            result = result * 37 + groupIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
