/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:36:41 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the td_sm_orggroup table.
 * This object should only be instantiated for use with instances of the
 * Orggroup class.
 */
public class OrggroupKey implements Serializable {
	/**
	 * The cached hash code value for this instance. Settting to 0 triggers
	 * re-calculation.
	 */
	private volatile int hashValue = 0;

	/** The value of the GROUP_ID component of this composite id. */
	private int groupId;

	/** The value of the ORG_ID component of this composite id. */
	private String orgId;

	/**
	 * Simple constructor of OrggroupKey instances.
	 */
	public OrggroupKey() {
	}

	/**
	 * Returns the value of the groupId property.
	 * 
	 * @return String
	 */
	public int getGroupId() {
		return groupId;
	}

	/**
	 * Sets the value of the groupId property.
	 * 
	 * @param groupId
	 */
	public void setGroupId(int groupId) {
		hashValue = 0;
		this.groupId = groupId;
	}

	/**
	 * Returns the value of the orgId property.
	 * 
	 * @return String
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * Sets the value of the orgId property.
	 * 
	 * @param orgId
	 */
	public void setOrgId(String orgId) {
		hashValue = 0;
		this.orgId = orgId;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the
	 * id components.
	 * 
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof OrggroupKey))
			return false;
		OrggroupKey that = (OrggroupKey) rhs;
		if (this.getGroupId() !=  that.getGroupId() ) {
			return false;
		}
		if (this.getOrgId() != null && that.getOrgId() != null) {
			if (!this.getOrgId().equals(that.getOrgId())) {
				return false;
			}
		}
		return true;
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern
	 * with the exception of array properties (these are very unlikely primary
	 * key types).
	 * 
	 * @return int
	 */
	public int hashCode() {
		if (this.hashValue == 0) {
			int result = 17;

			result = result * 37 + this.getGroupId();
			int orgIdValue = this.getOrgId() == null ? 0 : this.getOrgId()
					.hashCode();
			result = result * 37 + orgIdValue;
			this.hashValue = result;
		}
		return this.hashValue;
	}
}
