package com.frameworkset.platform.sysmgrcore.entity;
// Generated by MyEclipse - Hibernate Tools



/**
 * TdSmGrouprole generated by MyEclipse - Hibernate Tools
 */
public class Orgrole extends AbstractOrgrole implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Orgrole() {
    }
  
   
}
