/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:38:36 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the td_sm_userrole
 * table.  This object should only be instantiated for use with instances 
 * of the Userrole class.
 */
public class UserroleKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the USER_ID component of this composite id. */
    private Integer userId;

    /** The value of the ROLE_ID component of this composite id. */
    private String roleId;

    /**
     * Simple constructor of UserroleKey instances.
     */
    public UserroleKey()
    {
    }

    /**
     * Returns the value of the userId property.
     * @return String
     */
    public Integer getUserId()
    {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * @param userId
     */
    public void setUserId(Integer userId)
    {
        hashValue = 0;
        this.userId = userId;
    }

    /**
     * Returns the value of the roleId property.
     * @return String
     */
    public String getRoleId()
    {
        return roleId;
    }

    /**
     * Sets the value of the roleId property.
     * @param roleId
     */
    public void setRoleId(String roleId)
    {
        hashValue = 0;
        this.roleId = roleId;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof UserroleKey))
            return false;
        UserroleKey that = (UserroleKey) rhs;
        if (this.getUserId() != null && that.getUserId() != null)
        {
            if (! this.getUserId().equals(that.getUserId()))
            {
                return false;
            }
        }
        if (this.getRoleId() != null && that.getRoleId() != null)
        {
            if (! this.getRoleId().equals(that.getRoleId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int userIdValue = this.getUserId() == null ? 0 : this.getUserId().hashCode();
            result = result * 37 + userIdValue;
            int roleIdValue = this.getRoleId() == null ? 0 : this.getRoleId().hashCode();
            result = result * 37 + roleIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
