package com.sany.masterdata.hr.entity.userinfo;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-20T08:08:36.808+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "GetUserInfoList", wsdlLocation = "GetUserInfoList.wsdl", targetNamespace = "http://service.sany.com")
public class GetUserInfoList extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.sany.com", "GetUserInfoList");

    public final static QName GetUserInfoListHttpPort = new QName("http://service.sany.com", "GetUserInfoListHttpPort");
    static {
        URL url = GetUserInfoList.class.getResource("GetUserInfoList.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GetUserInfoList.class.getName()).log(java.util.logging.Level.INFO,
                    "Can not initialize the default wsdl from {0}", "GetUserInfoList.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetUserInfoList() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GetUserInfoList(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetUserInfoList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *         returns GetUserInfoListPortType
     */
    @WebEndpoint(name = "GetUserInfoListHttpPort")
    public GetUserInfoListPortType getGetUserInfoListHttpPort() {
        return super.getPort(GetUserInfoListHttpPort, GetUserInfoListPortType.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
     *            the <code>features</code> parameter will have their default values.
     * @return
     *         returns GetUserInfoListPortType
     */
    @WebEndpoint(name = "GetUserInfoListHttpPort")
    public GetUserInfoListPortType getGetUserInfoListHttpPort(WebServiceFeature... features) {
        return super.getPort(GetUserInfoListHttpPort, GetUserInfoListPortType.class, features);
    }

}
