package com.sany.masterdata.hr.entity.orginfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-10T20:04:34.302+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://service.sany.com", name = "GetOrgInfoListPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface GetOrgInfoListPortType {

    @WebResult(name = "out", targetNamespace = "http://service.sany.com")
    @RequestWrapper(localName = "getOrgList", targetNamespace = "http://service.sany.com", className = "com.sany.masterdata.hr.entity.orginfo.GetOrgList")
    @WebMethod
    @ResponseWrapper(localName = "getOrgListResponse", targetNamespace = "http://service.sany.com", className = "com.sany.masterdata.hr.entity.orginfo.GetOrgListResponse")
    public com.sany.masterdata.hr.entity.orginfo.ArrayOfOrgInfo getOrgList(
        @WebParam(name = "parameter", targetNamespace = "http://service.sany.com")
        com.sany.masterdata.hr.entity.orginfo.Parameter parameter
    );
}
