package com.frameworkset.common.tag.html;
import java.io.Serializable;

import javax.servlet.jsp.JspException;

import com.frameworkset.common.tag.BaseTag;


public class ScriptTag extends BaseTag implements Serializable{
	public int doStartTag() throws JspException{
		try{
			
			StringBuffer buffer = new StringBuffer();
			buffer.append("<SCRIPT LANGUAGE=\"JavaScript\">\n");
			buffer.append("var keyCode = 0;\n");
			buffer.append("var cacheResults = null;\n");
			buffer.append("var t_selectName,t_textfield;\n");
			buffer.append("var t_type,t_datasource;\n");
			buffer.append("function keyup(selectName,textfield,type,datasource){\n");
			buffer.append(" t_selectName = selectName;\n");
			buffer.append("t_textfield = textfield;\n");
			buffer.append("t_type = type;\n");
			buffer.append("t_datasource = datasource;\n");
			buffer.append("if(event.keyCode == 40 ||event.keyCode == 39 || event.keyCode == 38|| event.keyCode == 37)\n");
			buffer.append("{\n");
			buffer.append(" if(event.srcElement.name == t_selectName)\n");
			buffer.append("{\n");
			buffer.append("keyCode = 0;\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("else if(event.keyCode == 13)\n");
			buffer.append("{\n");
			buffer.append("if(event.srcElement.name == t_selectName)\n");
			buffer.append("{\n");
			buffer.append("keyCode = 0; \n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append(" else\n");
			buffer.append("{\n");
			buffer.append("var keywords =  document.all.item(t_textfield).value;\n");
			buffer.append("var result = lookup(keywords);\n");
			buffer.append("if(!result)\n");
			buffer.append("send_request('search.jsp?keywords='+keywords + '&type=' + t_type + '&datasource=' + t_datasource);\n");
			buffer.append("else\n");
			buffer.append("{\n");
			buffer.append("var results = result.split(\";\");\n");
			buffer.append("addall(results,t_selectName)\n");
			buffer.append("changestatus(selectName,textfield);\n");
			buffer.append("document.all(t_selectName).focus();\n");
			buffer.append("document.all(t_textfield).focus();\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("function lookup(key)\n");
			buffer.append("{\n");
			buffer.append("if(!cacheResults || !cacheResults.length)\n");
			buffer.append("return ;\n");
			buffer.append("for(i = 0; i < cacheResults.length; i ++)\n");
			buffer.append("{\n");
			buffer.append("var cacheResult = cacheResults[i];\n");
			buffer.append("if(cacheResult.key == key)\n");
			buffer.append("return cacheResult.value;\n");
			buffer.append("}\n");
			buffer.append("return ;\n");
			buffer.append("}\n");
			buffer.append("function CacheResult(key,value)\n");
			buffer.append("{\n");
			buffer.append("this.key = key;\n");
			buffer.append("this.value = value;\n");
			buffer.append("}\n");
			buffer.append("function keydown(selectName,textfield)\n");
			buffer.append("{\n");
			buffer.append("t_selectName = selectName; \n");
			buffer.append(" t_textfield = textfield;\n");
			buffer.append("if(event.keyCode == 40 ||event.keyCode == 39 || event.keyCode == 38|| event.keyCode == 37)\n");
			buffer.append("{\n");
			buffer.append("changestatus(selectName,textfield);\n");
			buffer.append("document.all(t_selectName).focus();\n");
			buffer.append("keyCode = event.keyCode;\n");
			buffer.append("}\n");
			buffer.append("else if(event.keyCode == 13 )\n");
			buffer.append("{\n");
			buffer.append("document.all.item(t_textfield).value=document.all.item(t_selectName).value;\n");
			//buffer.append("document.all(t_selectName).style.display=\"none\";\n");
			buffer.append("document.all(t_textfield).focus();\n");
			buffer.append("keyCode = 0;\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("var http_request = false;\n");
			buffer.append("function send_request(url){\n");
			buffer.append("if(window.XMLHttpRequest){\n");
			buffer.append("http_request = new XMLHttpRequest();\n");
			buffer.append("if(http_request.overrideMimeType){\n");
			buffer.append("http_request.overrideMimeType(\"text/xml\");\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("else if(window.ActiveXObject){\n");
			buffer.append("try{\n");
			buffer.append("http_request = new ActiveXObject(\"Msxml2.XMLHTTP\");\n");
			buffer.append("}catch(e){\n");
			buffer.append("try{\n");
			buffer.append("http_request = new ActiveXObject(\"Microsoft.XMLHTTP\");\n");
			buffer.append("}catch(e){\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("if(!http_request){\n");
			buffer.append("alert(\"不能创建XMLHttpRequest对象\");\n");
			buffer.append("return false;\n");
			buffer.append("}\n");
			buffer.append("http_request.onreadystatechange = processRequest;\n");
			buffer.append("http_request.open(\"GET\",url,true);\n");
			buffer.append("http_request.send(null);\n");
			buffer.append("}\n");
			buffer.append("function processRequest(){\n");
			buffer.append("if(http_request.readyState == 4){\n");
			buffer.append("if(http_request.status == 200){\n");
			buffer.append("var result = http_request.responseText;\n");
			buffer.append("var temp = result.split(\"$~$\");\n");
			buffer.append("var results = temp[1].split(\";\");\n");
			buffer.append("if(!cacheResults)\n");
			buffer.append("cacheResults = new Array();\n");
			buffer.append("cacheResults.push(new CacheResult(temp[0],temp[1]));\n");
			buffer.append("addall(results,t_selectName);\n");
			buffer.append("document.all(t_selectName).style.display=\"block\";\n");
			buffer.append("document.all(t_selectName).focus();\n");
			buffer.append("document.all(t_textfield).focus();\n");
			buffer.append("}\n");
			buffer.append("else{\n");
			buffer.append("alert(\"对不起，服务器错误\");\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("function addone(selectName,name,value){\n");
			buffer.append("var op=new Option(name,value);\n");
			buffer.append("document.all(selectName).add(op);\n");
			buffer.append("}\n");
			buffer.append("function deleteall(selectName){\n");
			buffer.append("for (var m = document.all(selectName).options.length-1; m >= 0; m--)\n");
			buffer.append("{\n");
			buffer.append("document.all(selectName).options[m] = null;\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("function addall(results,selectName){\n");
			buffer.append(" deleteall(selectName);\n");
			buffer.append("for(var i = 0; i < results.length; i++)\n");
			buffer.append("{\n");
			buffer.append(" addone(selectName,results[i], results[i]); \n");
			buffer.append(" }\n");
			buffer.append("}\n");
			buffer.append("function changestatus(selectName,textfield){\n");
			buffer.append("t_selectName = selectName;\n");
			buffer.append("t_textfield = textfield;\n");
            buffer.append(" document.all(t_selectName).style.display=\"block\";\n");
			buffer.append("}\n");
			buffer.append("function change(selectName,textfield){\n");
			buffer.append(" t_selectName = selectName;\n");
			buffer.append("t_textfield = textfield;\n");
			buffer.append("document.all(t_selectName).focus();\n");
			buffer.append("document.all.item(t_textfield).value=document.all.item(t_selectName).value;\n");
			buffer.append("if(keyCode == 40 ||keyCode == 39 || keyCode == 38 || keyCode == 37 )\n");
			buffer.append("{\n");
			buffer.append("}\n");
			buffer.append("else\n");
			buffer.append("{\n");
			//buffer.append("document.all(t_selectName).style.display=\"none\";\n");
			buffer.append("}\n");
			buffer.append("}\n");
			buffer.append("function checkselectStatus()\n");
			buffer.append("{\n");
			buffer.append("if(!event)\n");
			buffer.append("return ;\n");
			buffer.append("var eventName = event.srcElement.name ;\n");
			buffer.append("if(eventName == t_selectName || eventName == t_textfield)\n");
			buffer.append("return;\n");
			buffer.append("if(document.all(t_selectName).style.display ==\"block\")\n");
			buffer.append("document.all(t_selectName).style.display = \"none\";\n");
			buffer.append("}\n");
			buffer.append("</SCRIPT>\n");
		    out.print(buffer.toString());
			return EVAL_BODY_INCLUDE;
		}catch(Exception e){
		
			throw new JspException(e.getMessage());
		}
			
    }
}
