package com.sany.masterdata.hr.entity.jobinfo;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-21T17:19:31.537+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "GetJobInfoList", wsdlLocation = "GetJobInfoList.wsdl", targetNamespace = "http://service.sany.com")
public class GetJobInfoList extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.sany.com", "GetJobInfoList");

    public final static QName GetJobInfoListHttpPort = new QName("http://service.sany.com", "GetJobInfoListHttpPort");
    static {
        URL url = GetJobInfoList.class.getResource("GetJobInfoList.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GetJobInfoList.class.getName()).log(java.util.logging.Level.INFO,
                    "Can not initialize the default wsdl from {0}", "GetJobInfoList.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetJobInfoList() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GetJobInfoList(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetJobInfoList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *         returns GetJobInfoListPortType
     */
    @WebEndpoint(name = "GetJobInfoListHttpPort")
    public GetJobInfoListPortType getGetJobInfoListHttpPort() {
        return super.getPort(GetJobInfoListHttpPort, GetJobInfoListPortType.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
     *            the <code>features</code> parameter will have their default values.
     * @return
     *         returns GetJobInfoListPortType
     */
    @WebEndpoint(name = "GetJobInfoListHttpPort")
    public GetJobInfoListPortType getGetJobInfoListHttpPort(WebServiceFeature... features) {
        return super.getPort(GetJobInfoListHttpPort, GetJobInfoListPortType.class, features);
    }

}
