<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://service.sany.com" xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenc12="http://www.w3.org/2003/05/soap-encoding" xmlns:tns="http://service.sany.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedMXSD location="GetJobInfoList_InlineSchema1.mxsd"/>
        <binding hasEncoding="false" imported="true" name="GetJobInfoListHttpBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
<xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://service.sany.com">
<xsd:include schemaLocation="http://10.0.6.246:7800/GetJobInfoList?xsd=xsd0"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="getJobListRequest">
    <wsdl:part element="tns:getJobList" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getJobListResponse">
    <wsdl:part element="tns:getJobListResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="GetJobInfoListPortType">
    <wsdl:operation name="getJobList">
      <wsdl:input message="tns:getJobListRequest" name="getJobListRequest">
    </wsdl:input>
      <wsdl:output message="tns:getJobListResponse" name="getJobListResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GetJobInfoListHttpBinding" type="tns:GetJobInfoListPortType">
    <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getJobList">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="getJobListRequest">
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getJobListResponse">
        <wsdlsoap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetJobInfoList">
    <wsdl:port binding="tns:GetJobInfoListHttpBinding" name="GetJobInfoListHttpPort">
      <wsdlsoap:address location="http://10.0.6.246:7800/GetJobInfoList"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>