package com.sany.masterdata.hr.entity.jobinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-21T17:19:31.443+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://service.sany.com", name = "GetJobInfoListPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface GetJobInfoListPortType {

    @WebResult(name = "out", targetNamespace = "http://service.sany.com")
    @RequestWrapper(localName = "getJobList", targetNamespace = "http://service.sany.com", className = "com.sany.masterdata.hr.entity.jobinfo.GetJobList")
    @WebMethod
    @ResponseWrapper(localName = "getJobListResponse", targetNamespace = "http://service.sany.com", className = "com.sany.masterdata.hr.entity.jobinfo.GetJobListResponse")
    public com.sany.masterdata.hr.entity.jobinfo.ArrayOfJobInfo getJobList(
            @WebParam(name = "parameter", targetNamespace = "http://service.sany.com") com.sany.masterdata.hr.entity.jobinfo.Parameter parameter);
}
