package com.sany.masterdata.hr.entity.userinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-20T08:08:36.730+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://service.sany.com", name = "GetUserInfoListPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface GetUserInfoListPortType {

    @WebResult(name = "out", targetNamespace = "http://service.sany.com")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://service.sany.com", className = "com.sany.masterdata.webservices.entity.userinfo.GetUserList")
    @WebMethod
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://service.sany.com", className = "com.sany.masterdata.webservices.entity.userinfo.GetUserListResponse")
    public com.sany.masterdata.hr.entity.userinfo.ArrayOfUserInfo getUserList(
            @WebParam(name = "parameter", targetNamespace = "http://service.sany.com") com.sany.masterdata.hr.entity.userinfo.Parameter parameter);
}
