/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:36:16 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the td_sm_operreg table. You can customize
 * the behavior of this class by editing the class, {@link Operres()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized *
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractOperres implements Serializable {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** The simple primary key value. */
    private OperresKey id = new OperresKey();

    /**
     * 所关联的操作实体
     */
    private Operation operation = null;

    /**
     * 所关联的资源实体
     */
    private Res res = null;

    /**
     * @return 返回 operation。
     */
    public Operation getOperation() {
        return operation;
    }

    /**
     * @param operation
     *            要设置的 operation。
     */
    public void setOperation(Operation operation) {
        this.operation = operation;

        if (id.getOpId() == null && operation != null)
            id.setOpId(operation.getOpId());
    }

    /**
     * @return 返回 res。
     */
    public Res getRes() {
        return res;
    }

    /**
     * @param res
     *            要设置的 res。
     */
    public void setRes(Res res) {
        this.res = res;

        if (id.getResId() == null && res != null)
            id.setResId(res.getResId());
    }

    /**
     * Simple constructor of AbstractOperres instances.
     */
    public AbstractOperres() {
    }

    /**
     * Constructor of AbstractOperres instances given a composite primary
     * key.
     * 
     * @param id
     */
    public AbstractOperres(OperresKey id) {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * 
     * @return OperresKey
     */
    public OperresKey getId() {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * 
     * @param id
     */
    public void setId(OperresKey id) {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Operres))
            return false;
        Operres that = (Operres) rhs;
        if (this.getId() != null && that.getId() != null) {
            return (this.getId().equals(that.getId()));
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            if (this.getId() == null) {
                result = super.hashCode();
            } else {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
}