package com.frameworkset.platform.sysmgrcore.entity;

/**
 * AbstractTdSmGrouprole generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractOrgrole implements java.io.Serializable {

	// Fields

	private OrgroleId id = new OrgroleId();

	/**
	 * 所关联的组对象实例
	 */
	private Organization organization;

	/**
	 * 所关联的角色对象实例
	 */
	private Role role;

	// Constructors

	/** default constructor */
	public AbstractOrgrole() {
	}

	// Property accessors

	public OrgroleId getId() {
		return this.id;
	}

	public void setId(OrgroleId id) {
		this.id = id;
	}

	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
		
		if (id.getOrgId() == null && organization != null)
			id.setOrgId(organization.getOrgId());
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
		
		if (id.getRoleId() == null && role != null)
			id.setRoleId(role.getRoleId());
	}
}