/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:36:49 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;


/**
 * A class that represents a row in the td_sm_orgjob table. You can customize
 * the behavior of this class by editing the class, {@link Orgjob()}. WARNING:
 * DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by
 * MyEclipse Hibernate tool integration.
 */
public abstract class AbstractOrgjob  implements Serializable {

	/** The simple primary key value. */
	private OrgjobKey id = new OrgjobKey();

	/**
	 * 岗位在机构中的顺序号
	 */
	private Integer jobSn;

	/**
	 * 所关联的机构实体
	 */
	private Organization organization = null;

	/**
	 * 所关联的岗位实体
	 */
	private Job job = null;

	/**
	 * @return 返回 organization。
	 */
	public Organization getOrganization() {
		return organization;
	}

	/**
	 * @param organization
	 *            要设置的 organization。
	 */
	public void setOrganization(Organization organization) {
		this.organization = organization;

		if (id.getOrgId() == null && organization != null)
			id.setOrgId(organization.getOrgId());
	}

	/**
	 * @return 返回 job。
	 */
	public Job getJob() {
		return job;
	}

	/**
	 * @param job
	 *            要设置的 job。
	 */
	public void setJob(Job job) {
		this.job = job;

		if (id.getJobId() == null && job != null)
			id.setJobId(job.getJobId());
	}

	/**
	 * Simple constructor of AbstractOrgjob instances.
	 */
	public AbstractOrgjob() {
	}

	/**
	 * Constructor of AbstractOrgjob instances given a composite primary key.
	 * 
	 * @param id
	 */
	public AbstractOrgjob(OrgjobKey id) {
		this.setId(id);
	}

	/**
	 * Return the composite id instance that identifies this object.
	 * 
	 * @return OrgjobKey
	 */
	public OrgjobKey getId() {
		return this.id;
	}

	/**
	 * Set the composite id instance that identifies this object.
	 * 
	 * @param id
	 */
	public void setId(OrgjobKey id) {
		this.id = id;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the
	 * primary key values.
	 * 
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof Orgjob))
			return false;
		Orgjob that = (Orgjob) rhs;
		if (this.getId() != null && that.getId() != null) {
			return (this.getId().equals(that.getId()));
		}
		return true;
	}


	public Integer getJobSn() {
		return jobSn;
	}

	public void setJobSn(Integer jobSn) {
		this.jobSn = jobSn;
	}
}
