/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:35:56 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the td_sm_listdictdata table. 
 * You can customize the behavior of this class by editing the class, {@link Listdictdata()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractListdictdata 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private String listdicdataId;

    /** The value of the simple listdictId property. */
    private String listdictId;

    /** The value of the simple listdicdataName property. */
    private String listdicdataName;

    /** The value of the simple value property. */
    private String value;

    /** The value of the simple jp property. */
    private String jp;

    /** The value of the simple qp property. */
    private String qp;

    /** The value of the simple remark1 property. */
    private String remark1;

    /** The value of the simple remark2 property. */
    private String remark2;

    /** The value of the simple remark3 property. */
    private String remark3;

    /**
     * Simple constructor of AbstractListdictdata instances.
     */
    public AbstractListdictdata()
    {
    }

    /**
     * Constructor of AbstractListdictdata instances given a simple primary key.
     * @param listdicdataId
     */
    public AbstractListdictdata(String listdicdataId)
    {
        this.setListdicdataId(listdicdataId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return String
     */
    public String getListdicdataId()
    {
        return listdicdataId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param listdicdataId
     */
    public void setListdicdataId(String listdicdataId)
    {
        this.hashValue = 0;
        this.listdicdataId = listdicdataId;
    }

    /**
     * Return the value of the LISTDICT_ID column.
     * @return String
     */
    public String getListdictId()
    {
        return this.listdictId;
    }

    /**
     * Set the value of the LISTDICT_ID column.
     * @param listdictId
     */
    public void setListdictId(String listdictId)
    {
        this.listdictId = listdictId;
    }

    /**
     * Return the value of the LISTDICDATA_NAME column.
     * @return String
     */
    public String getListdicdataName()
    {
        return this.listdicdataName;
    }

    /**
     * Set the value of the LISTDICDATA_NAME column.
     * @param listdicdataName
     */
    public void setListdicdataName(String listdicdataName)
    {
        this.listdicdataName = listdicdataName;
    }

    /**
     * Return the value of the VALUE column.
     * @return String
     */
    public String getValue()
    {
        return this.value;
    }

    /**
     * Set the value of the VALUE column.
     * @param value
     */
    public void setValue(String value)
    {
        this.value = value;
    }

    /**
     * Return the value of the JP column.
     * @return String
     */
    public String getJp()
    {
        return this.jp;
    }

    /**
     * Set the value of the JP column.
     * @param jp
     */
    public void setJp(String jp)
    {
        this.jp = jp;
    }

    /**
     * Return the value of the QP column.
     * @return String
     */
    public String getQp()
    {
        return this.qp;
    }

    /**
     * Set the value of the QP column.
     * @param qp
     */
    public void setQp(String qp)
    {
        this.qp = qp;
    }

    /**
     * Return the value of the REMARK1 column.
     * @return String
     */
    public String getRemark1()
    {
        return this.remark1;
    }

    /**
     * Set the value of the REMARK1 column.
     * @param remark1
     */
    public void setRemark1(String remark1)
    {
        this.remark1 = remark1;
    }

    /**
     * Return the value of the REMARK2 column.
     * @return String
     */
    public String getRemark2()
    {
        return this.remark2;
    }

    /**
     * Set the value of the REMARK2 column.
     * @param remark2
     */
    public void setRemark2(String remark2)
    {
        this.remark2 = remark2;
    }

    /**
     * Return the value of the REMARK3 column.
     * @return String
     */
    public String getRemark3()
    {
        return this.remark3;
    }

    /**
     * Set the value of the REMARK3 column.
     * @param remark3
     */
    public void setRemark3(String remark3)
    {
        this.remark3 = remark3;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Listdictdata))
            return false;
        Listdictdata that = (Listdictdata) rhs;
        if (this.getListdicdataId() != null && that.getListdicdataId() != null)
        {
            if (! this.getListdicdataId().equals(that.getListdicdataId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int listdicdataIdValue = this.getListdicdataId() == null ? 0 : this.getListdicdataId().hashCode();
            result = result * 37 + listdicdataIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
