/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:37:05 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the td_sm_reslog table. You can customize
 * the behavior of this class by editing the class, {@link Reslog()}. WARNING:
 * DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by
 * MyEclipse Hibernate tool integration.
 */
public abstract class AbstractReslog implements Serializable {
	/**
	 * The cached hash code value for this instance. Settting to 0 triggers
	 * re-calculation.
	 */
	private int hashValue = 0;

	/** The composite primary key value. */
	private String reslogId;

	/** The value of the simple opId property. */
	private String opId;

	/** The value of the simple resId property. */
	private String resId;

	/** The value of the simple userId property. */
	private Integer userId;

	/** The value of the simple reslogDate property. */
	private java.util.Date reslogDate;

	/**
	 * Simple constructor of AbstractReslog instances.
	 */
	public AbstractReslog() {
	}

	/**
	 * Constructor of AbstractReslog instances given a simple primary key.
	 * 
	 * @param reslogId
	 */
	public AbstractReslog(String reslogId) {
		this.setReslogId(reslogId);
	}

	/**
	 * Return the simple primary key value that identifies this object.
	 * 
	 * @return String
	 */
	public String getReslogId() {
		return reslogId;
	}

	/**
	 * Set the simple primary key value that identifies this object.
	 * 
	 * @param reslogId
	 */
	public void setReslogId(String reslogId) {
		this.hashValue = 0;
		this.reslogId = reslogId;
	}

	/**
	 * Return the value of the OP_ID column.
	 * 
	 * @return String
	 */
	public String getOpId() {
		return this.opId;
	}

	/**
	 * Set the value of the OP_ID column.
	 * 
	 * @param opId
	 */
	public void setOpId(String opId) {
		this.opId = opId;
	}

	/**
	 * Return the value of the RES_ID column.
	 * 
	 * @return String
	 */
	public String getResId() {
		return this.resId;
	}

	/**
	 * Set the value of the RES_ID column.
	 * 
	 * @param resId
	 */
	public void setResId(String resId) {
		this.resId = resId;
	}

	/**
	 * Return the value of the USER_ID column.
	 * 
	 * @return String
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the value of the USER_ID column.
	 * 
	 * @param userId
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Return the value of the RESLOG_DATE column.
	 * 
	 * @return java.util.Date
	 */
	public java.util.Date getReslogDate() {
		return this.reslogDate;
	}

	/**
	 * Set the value of the RESLOG_DATE column.
	 * 
	 * @param reslogDate
	 */
	public void setReslogDate(java.util.Date reslogDate) {
		this.reslogDate = reslogDate;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the
	 * primary key values.
	 * 
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof Reslog))
			return false;
		Reslog that = (Reslog) rhs;
		if (this.getReslogId() != null && that.getReslogId() != null) {
			if (!this.getReslogId().equals(that.getReslogId())) {
				return false;
			}
		}
		return true;
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern
	 * with the exception of array properties (these are very unlikely primary
	 * key types).
	 * 
	 * @return int
	 */
	public int hashCode() {
		if (this.hashValue == 0) {
			int result = 17;
			int reslogIdValue = this.getReslogId() == null ? 0 : this
					.getReslogId().hashCode();
			result = result * 37 + reslogIdValue;
			this.hashValue = result;
		}
		return this.hashValue;
	}
}
