/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:35:07 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the td_sm_hiedict table. 
 * You can customize the behavior of this class by editing the class, {@link Hiedict()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractHiedict 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private String hiedictId;

    /** The value of the simple name property. */
    private String name;

    /** The value of the simple rootId property. */
    private String rootId;

    /**
     * Simple constructor of AbstractHiedict instances.
     */
    public AbstractHiedict()
    {
    }

    /**
     * Constructor of AbstractHiedict instances given a simple primary key.
     * @param hiedictId
     */
    public AbstractHiedict(String hiedictId)
    {
        this.setHiedictId(hiedictId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return String
     */
    public String getHiedictId()
    {
        return hiedictId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param hiedictId
     */
    public void setHiedictId(String hiedictId)
    {
        this.hashValue = 0;
        this.hiedictId = hiedictId;
    }

    /**
     * Return the value of the NAME column.
     * @return String
     */
    public String getName()
    {
        return this.name;
    }

    /**
     * Set the value of the NAME column.
     * @param name
     */
    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * Return the value of the ROOT_ID column.
     * @return String
     */
    public String getRootId()
    {
        return this.rootId;
    }

    /**
     * Set the value of the ROOT_ID column.
     * @param rootId
     */
    public void setRootId(String rootId)
    {
        this.rootId = rootId;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Hiedict))
            return false;
        Hiedict that = (Hiedict) rhs;
        if (this.getHiedictId() != null && that.getHiedictId() != null)
        {
            if (! this.getHiedictId().equals(that.getHiedictId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int hiedictIdValue = this.getHiedictId() == null ? 0 : this.getHiedictId().hashCode();
            result = result * 37 + hiedictIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
