/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:35:40 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the td_sm_listdict table. 
 * You can customize the behavior of this class by editing the class, {@link Listdict()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractListdict 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private String listdictId;

    /** The value of the simple listdictName property. */
    private String listdictName;

    /** The value of the simple dictype property. */
    private String dictype;

    /**
     * Simple constructor of AbstractListdict instances.
     */
    public AbstractListdict()
    {
    }

    /**
     * Constructor of AbstractListdict instances given a simple primary key.
     * @param listdictId
     */
    public AbstractListdict(String listdictId)
    {
        this.setListdictId(listdictId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return String
     */
    public String getListdictId()
    {
        return listdictId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param listdictId
     */
    public void setListdictId(String listdictId)
    {
        this.hashValue = 0;
        this.listdictId = listdictId;
    }

    /**
     * Return the value of the LISTDICT_NAME column.
     * @return String
     */
    public String getListdictName()
    {
        return this.listdictName;
    }

    /**
     * Set the value of the LISTDICT_NAME column.
     * @param listdictName
     */
    public void setListdictName(String listdictName)
    {
        this.listdictName = listdictName;
    }

    /**
     * Return the value of the DICTYPE column.
     * @return String
     */
    public String getDictype()
    {
        return this.dictype;
    }

    /**
     * Set the value of the DICTYPE column.
     * @param dictype
     */
    public void setDictype(String dictype)
    {
        this.dictype = dictype;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Listdict))
            return false;
        Listdict that = (Listdict) rhs;
        if (this.getListdictId() != null && that.getListdictId() != null)
        {
            if (! this.getListdictId().equals(that.getListdictId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int listdictIdValue = this.getListdictId() == null ? 0 : this.getListdictId().hashCode();
            result = result * 37 + listdictIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
