/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:35:17 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class that represents a row in the td_sm_hiedictdata table. 
 * You can customize the behavior of this class by editing the class, {@link Hiedictdata()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractHiedictdata 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private String hiedictdataId;

    /** The value of the simple hiedictId property. */
    private String hiedictId;

    /** The value of the simple parentId property. */
    private String parentId;

    /** The value of the simple hiedictdataName property. */
    private String hiedictdataName;

    /** The value of the simple value property. */
    private String value;

    /** The value of the simple jp property. */
    private String jp;

    /** The value of the simple qp property. */
    private String qp;

    /** The value of the simple hiedictdataType property. */
    private String hiedictdataType;

    /**
     * Simple constructor of AbstractHiedictdata instances.
     */
    public AbstractHiedictdata()
    {
    }

    /**
     * Constructor of AbstractHiedictdata instances given a simple primary key.
     * @param hiedictdataId
     */
    public AbstractHiedictdata(String hiedictdataId)
    {
        this.setHiedictdataId(hiedictdataId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return String
     */
    public String getHiedictdataId()
    {
        return hiedictdataId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param hiedictdataId
     */
    public void setHiedictdataId(String hiedictdataId)
    {
        this.hashValue = 0;
        this.hiedictdataId = hiedictdataId;
    }

    /**
     * Return the value of the HIEDICT_ID column.
     * @return String
     */
    public String getHiedictId()
    {
        return this.hiedictId;
    }

    /**
     * Set the value of the HIEDICT_ID column.
     * @param hiedictId
     */
    public void setHiedictId(String hiedictId)
    {
        this.hiedictId = hiedictId;
    }

    /**
     * Return the value of the PARENT_ID column.
     * @return String
     */
    public String getParentId()
    {
        return this.parentId;
    }

    /**
     * Set the value of the PARENT_ID column.
     * @param parentId
     */
    public void setParentId(String parentId)
    {
        this.parentId = parentId;
    }

    /**
     * Return the value of the HIEDICTDATA_NAME column.
     * @return String
     */
    public String getHiedictdataName()
    {
        return this.hiedictdataName;
    }

    /**
     * Set the value of the HIEDICTDATA_NAME column.
     * @param hiedictdataName
     */
    public void setHiedictdataName(String hiedictdataName)
    {
        this.hiedictdataName = hiedictdataName;
    }

    /**
     * Return the value of the VALUE column.
     * @return String
     */
    public String getValue()
    {
        return this.value;
    }

    /**
     * Set the value of the VALUE column.
     * @param value
     */
    public void setValue(String value)
    {
        this.value = value;
    }

    /**
     * Return the value of the JP column.
     * @return String
     */
    public String getJp()
    {
        return this.jp;
    }

    /**
     * Set the value of the JP column.
     * @param jp
     */
    public void setJp(String jp)
    {
        this.jp = jp;
    }

    /**
     * Return the value of the QP column.
     * @return String
     */
    public String getQp()
    {
        return this.qp;
    }

    /**
     * Set the value of the QP column.
     * @param qp
     */
    public void setQp(String qp)
    {
        this.qp = qp;
    }

    /**
     * Return the value of the HIEDICTDATA_TYPE column.
     * @return String
     */
    public String getHiedictdataType()
    {
        return this.hiedictdataType;
    }

    /**
     * Set the value of the HIEDICTDATA_TYPE column.
     * @param hiedictdataType
     */
    public void setHiedictdataType(String hiedictdataType)
    {
        this.hiedictdataType = hiedictdataType;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Hiedictdata))
            return false;
        Hiedictdata that = (Hiedictdata) rhs;
        if (this.getHiedictdataId() != null && that.getHiedictdataId() != null)
        {
            if (! this.getHiedictdataId().equals(that.getHiedictdataId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int hiedictdataIdValue = this.getHiedictdataId() == null ? 0 : this.getHiedictdataId().hashCode();
            result = result * 37 + hiedictdataIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
