/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Mar 17 08:40:14 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the TD_SM_OPERGPRESTYPE
 * table. This object should only be instantiated for use with instances of the
 * Opergprestype class.
 */
public class OpergprestypeKey implements Serializable {
	/**
	 * The cached hash code value for this instance. Settting to 0 triggers
	 * re-calculation.
	 */
	private volatile int hashValue = 0;

	private String groupId;

	private String restypeId;

	/**
	 * Simple constructor of OpergprestypeKey instances.
	 */
	public OpergprestypeKey() {
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		hashValue = 0;
		this.groupId = groupId;
	}

	public String getRestypeId() {
		return restypeId;
	}

	public void setRestypeId(String restypeId) {
		hashValue = 0;
		this.restypeId = restypeId;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the
	 * id components.
	 * 
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof OpergprestypeKey))
			return false;
		OpergprestypeKey that = (OpergprestypeKey) rhs;
		if (this.getRestypeId() != null && that.getRestypeId() != null) {
			if (!this.getRestypeId().equals(that.getRestypeId())) {
				return false;
			}
		}
		if (this.getGroupId() != null && that.getGroupId() != null) {
			if (!this.getGroupId().equals(that.getGroupId())) {
				return false;
			}
		}
		return true;
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern
	 * with the exception of array properties (these are very unlikely primary
	 * key types).
	 * 
	 * @return int
	 */
	public int hashCode() {
		if (this.hashValue == 0) {
			int result = 17;
			int restypeIdValue = this.getRestypeId() == null ? 0 : this
					.getRestypeId().hashCode();
			result = result * 37 + restypeIdValue;
			int groupIdValue = this.getGroupId() == null ? 0 : this
					.getGroupId().hashCode();
			result = result * 37 + groupIdValue;
			this.hashValue = result;
		}
		return this.hashValue;
	}
}
