/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:36:49 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the td_sm_orgjob
 * table.  This object should only be instantiated for use with instances 
 * of the Orgjob class.
 */
public class OrgjobKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the ORG_ID component of this composite id. */
    private String orgId;

    /** The value of the JOB_ID component of this composite id. */
    private String jobId;

    /**
     * Simple constructor of OrgjobKey instances.
     */
    public OrgjobKey()
    {
    }

    /**
     * Returns the value of the orgId property.
     * @return String
     */
    public String getOrgId()
    {
        return orgId;
    }

    /**
     * Sets the value of the orgId property.
     * @param orgId
     */
    public void setOrgId(String orgId)
    {
        hashValue = 0;
        this.orgId = orgId;
    }

    /**
     * Returns the value of the jobId property.
     * @return String
     */
    public String getJobId()
    {
        return jobId;
    }

    /**
     * Sets the value of the jobId property.
     * @param jobId
     */
    public void setJobId(String jobId)
    {
        hashValue = 0;
        this.jobId = jobId;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof OrgjobKey))
            return false;
        OrgjobKey that = (OrgjobKey) rhs;
        if (this.getOrgId() != null && that.getOrgId() != null)
        {
            if (! this.getOrgId().equals(that.getOrgId()))
            {
                return false;
            }
        }
        if (this.getJobId() != null && that.getJobId() != null)
        {
            if (! this.getJobId().equals(that.getJobId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int orgIdValue = this.getOrgId() == null ? 0 : this.getOrgId().hashCode();
            result = result * 37 + orgIdValue;
            int jobIdValue = this.getJobId() == null ? 0 : this.getJobId().hashCode();
            result = result * 37 + jobIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
