/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Feb 08 15:37:24 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.frameworkset.platform.sysmgrcore.entity;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the td_sm_roleresop
 * table.  This object should only be instantiated for use with instances 
 * of the Roleresop class.
 */
public class RoleresopKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the OP_ID component of this composite id. */
    private String opId;

    /** The value of the RES_ID component of this composite id. */
    private String resId;

    /** The value of the ROLE_ID component of this composite id. */
    private String roleId;
    private String restypeId;
    /**
     * Simple constructor of RoleresopKey instances.
     */
    public RoleresopKey()
    {
    }

    /**
     * Returns the value of the opId property.
     * @return String
     */
    public String getOpId()
    {
        return opId;
    }

    /**
     * Sets the value of the opId property.
     * @param opId
     */
    public void setOpId(String opId)
    {
        hashValue = 0;
        this.opId = opId;
    }

    /**
     * Returns the value of the resId property.
     * @return String
     */
    public String getResId()
    {
        return resId;
    }

    /**
     * Sets the value of the resId property.
     * @param resId
     */
    public void setResId(String resId)
    {
        hashValue = 0;
        this.resId = resId;
    }

    /**
     * Returns the value of the roleId property.
     * @return String
     */
    public String getRoleId()
    {
        return roleId;
    }

    /**
     * Sets the value of the roleId property.
     * @param roleId
     */
    public void setRoleId(String roleId)
    {
        hashValue = 0;
        this.roleId = roleId;
    }

    /**
     * Returns the value of the restypeId property.
     * @return String
     */
    public String getRestypeId()
    {
        return restypeId;
    }

    /**
     * Sets the value of the roleId property.
     * @param roleId
     */
    public void setRestypeId(String restypeId)
    {
        hashValue = 0;
        this.restypeId = restypeId;
    }
    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof RoleresopKey))
            return false;
        RoleresopKey that = (RoleresopKey) rhs;
        if (this.getOpId() != null && that.getOpId() != null)
        {
            if (! this.getOpId().equals(that.getOpId()))
            {
                return false;
            }
        }
        if (this.getResId() != null && that.getResId() != null)
        {
            if (! this.getResId().equals(that.getResId()))
            {
                return false;
            }
        }
        if (this.getRoleId() != null && that.getRoleId() != null)
        {
            if (! this.getRoleId().equals(that.getRoleId()))
            {
                return false;
            }
        }
        if (this.getRestypeId() != null && that.getRestypeId() != null)
        {
            if (! this.getRestypeId().equals(that.getRestypeId()))
            {
                return false;
            }
        }        
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int opIdValue = this.getOpId() == null ? 0 : this.getOpId().hashCode();
            result = result * 37 + opIdValue;
            int resIdValue = this.getResId() == null ? 0 : this.getResId().hashCode();
            result = result * 37 + resIdValue;
            int roleIdValue = this.getRoleId() == null ? 0 : this.getRoleId().hashCode();
            result = result * 37 + roleIdValue;
            int restypeIdValue = this.getRestypeId() == null ? 0 : this.getRestypeId().hashCode();
            result = result * 37 + restypeIdValue;            
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
