package com.sany.masterdata.hr.entity.orginfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-10T20:04:34.381+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "GetOrgInfoList", 
                  wsdlLocation = "GetOrgInfoList.wsdl",
                  targetNamespace = "http://service.sany.com") 
public class GetOrgInfoList extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.sany.com", "GetOrgInfoList");
    public final static QName GetOrgInfoListHttpPort = new QName("http://service.sany.com", "GetOrgInfoListHttpPort");
    static {
        URL url = GetOrgInfoList.class.getResource("GetOrgInfoList.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GetOrgInfoList.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "GetOrgInfoList.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public GetOrgInfoList(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetOrgInfoList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetOrgInfoList() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetOrgInfoListPortType
     */
    @WebEndpoint(name = "GetOrgInfoListHttpPort")
    public GetOrgInfoListPortType getGetOrgInfoListHttpPort() {
        return super.getPort(GetOrgInfoListHttpPort, GetOrgInfoListPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetOrgInfoListPortType
     */
    @WebEndpoint(name = "GetOrgInfoListHttpPort")
    public GetOrgInfoListPortType getGetOrgInfoListHttpPort(WebServiceFeature... features) {
        return super.getPort(GetOrgInfoListHttpPort, GetOrgInfoListPortType.class, features);
    }

}
